baseURL = "http://pages.github.com/" # Please enter your githubpage's url here
languageCode = "en-us"
title = "My Latex Notes"
theme = "hyde"


[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/username/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]

[params]
  description = "Alright boi, keep your notes here"
